import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LanguageApp',
  description: 'Generated by create next app',

}

export default async function RootLayout({children}: {children: React.ReactNode}) {  
  return (

      <html lang="en">
        <body>{children}</body>
      </html>

  )
}
